### ISSUE TITLE
Can't save when adding localized fields

### ISSUE THREAD

**Issue by abel-sch** [payloadcms/payload-3.0-demo#102]
When trying to publish a document with a localized field I get an error and fail to save.

I'm trying a minimal setup:
```
export const Pages: CollectionConfig = {
  slug: 'pages',
  fields: [
    {
      name: 'title',
      label: 'Title',
      type: 'text',
      localized: true,
      required: true,
    },
  ],
}
```

Which gives me this db error:
```ERROR: TypeError: Cannot read properties of undefined (reading 'Symbol(drizzle:Columns)')```

Localization config:
```
  localization: {
    locales: ['nl', 'en'],
    defaultLocale: 'en',
    fallback: false,
  },
  ```
  
 Maybe relevant; I'm using Vercel Postgress

**Comment by jmikrut** [comment]
Hey @abel-sch — so this is caused by one of two things:

#### 1. Database entity names are too long

You might have table names or index names that are longer than the Postgres limit of 64 characters. To work around this, you can use a new `dbName` property in your config to ensure that your table / index names are less than the max of 64 characters. You can define `dbName` on collections, blocks fields, array fields, etc. This is not happening in your example config's code, because all DB entity names are well-within the 64 character limit, so if this is indeed the cause of the error,  we'd need to see your whole config to help pinpoint where this is happening.

#### 2. You have not run migrations

Is this error showing up in your local environment, or in your deployed environment? If it's showing up in your deployed, you might not have run migrations against your production database. 

We will need a minimally reproducible environment to be able to help test this, because with your provided structure, everything works when we try it.  Let me know if you can narrow it down to one of the two above options. I'll keep an eye out!

**Comment by abel-sch** [comment]
Hi @jmikrut ,

I appreciate your quick reply but I think you're quite hasty with closing down this issue... As stated in the issue the table name is pages, and the field name is title so nowhere near the 64 character limit.
A proper error message would be appreciated if this would be the case tough.

When I add `localized: true` to the fields configuration I get this warning: 
```· You're about to delete title column in pages table with 3 items

DATA LOSS WARNING: Possible data loss detected if schema is pushed.
```

I can imagine you have to define the fields localization on forehand (which might cause some issues in real life scenarios) but once I accept the warning the title field disappears followed by this error in the terminal:

```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
 ⨯ TypeError: Cannot read properties of null (reading 'useContext')
    at usePathname (/Users/abelschupp/Desktop/proto/boilerpayload/.next/server/chunks/node_modules_909a51._.js:4681:238)
    at ErrorBoundary (/Users/abelschupp/Desktop/proto/boilerpayload/.next/server/chunks/node_modules_909a51._.js:4992:227)
digest: "2405498236"
```

The title field does render in the CMS but submitted gives me a 'Something went wrong...' error, probably due to the field not existing in the database table. A more concise error message here would be very welcome.
