### ISSUE TITLE
Clicking collections links in the nav may crash admin panel

### ISSUE THREAD

**Issue by r1tsuu** [payloadcms/payload-3.0-demo#106]
https://github.com/payloadcms/payload-3.0-demo/assets/64744993/945ced74-c2f8-4d97-8b9d-fc048405d93c

**Comment by AlessioGr** [comment]
Are you getting any errors in your browser / server console when this happens?

**Comment by r1tsuu** [comment]
> Are you getting any errors in your browser / server console when this happens?

i uploaded the video, yes there are errors

**Comment by r1tsuu** [comment]
> Are you getting any errors in your browser / server console when this happens?

oh, i clipped the video so much that you cant see console

**Comment by r1tsuu** [comment]
> Are you getting any errors in your browser / server console when this happens?

`
index.tsx:82 Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at ListControls (index.tsx:82:33)
    at renderWithHooks (react-dom.development.js:11121:18)
    at mountIndeterminateComponent (react-dom.development.js:16869:13)
    at beginWork$1 (react-dom.development.js:18458:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:20565:14)
    at Object.invokeGuardedCallbackImpl (react-dom.development.js:20614:16)
    at invokeGuardedCallback (react-dom.development.js:20689:29)
    at beginWork (react-dom.development.js:26949:7)
    at performUnitOfWork (react-dom.development.js:25748:12)
    at workLoopConcurrent (react-dom.development.js:25734:5)
    at renderRootConcurrent (react-dom.development.js:25690:9)
    at performConcurrentWorkOnRoot (react-dom.development.js:24504:38)
    at workLoop (scheduler.development.js:256:34)
    at flushWork (scheduler.development.js:225:14)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:534:21)
`

**Comment by paulpopus** [comment]
Fixed in https://github.com/payloadcms/payload/pull/5850
