### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'referencedTable')

### ISSUE THREAD

**Issue by oladayo21** [payloadcms/payload-3.0-demo#108]
I am getting this error whenever I edit something in my `payload.config.ts` file and the next dev server hot reloads. It only starts to work again after i restart the server
```
Internal error: TypeError: Cannot read properties of undefined (reading 'referencedTable')
    at normalizeRelation (./node_modules/.pnpm/drizzle-orm@0.29.4_@libsql+client@0.5.6_@types+react@18.2.78_pg@8.11.3_react@18.2.0/node_modules/drizzle-orm/relations.js:211:56)
    at PgDialect.buildRelationalQueryWithoutPK (./node_modules/.pnpm/drizzle-orm@0.29.4_@libsql+client@0.5.6_@types+react@18.2.78_pg@8.11.3_react@18.2.0/node_modules/drizzle-orm/pg-core/dialect.js:963:101)
    at QueryPromise._getQuery (./node_modules/.pnpm/drizzle-orm@0.29.4_@libsql+client@0.5.6_@types+react@18.2.78_pg@8.11.3_react@18.2.0/node_modules/drizzle-orm/pg-core/query-builders/query.js:90:25)
    at QueryPromise._toSQL (./node_modules/.pnpm/drizzle-orm@0.29.4_@libsql+client@0.5.6_@types+react@18.2.78_pg@8.11.3_react@18.2.0/node_modules/drizzle-orm/pg-core/query-builders/query.js:105:24)
    at eval (./node_modules/.pnpm/drizzle-orm@0.29.4_@libsql+client@0.5.6_@types+react@18.2.78_pg@8.11.3_react@18.2.0/node_modules/drizzle-orm/pg-core/query-builders/query.js:69:42)
    at Object.startActiveSpan (./node_modules/.pnpm/drizzle-orm@0.29.4_@libsql+client@0.5.6_@types+react@18.2.78_pg@8.11.3_react@18.2.0/node_modules/drizzle-orm/tracing.js:14:14)
    at QueryPromise._prepare (./node_modules/.pnpm/drizzle-orm@0.29.4_@libsql+client@0.5.6_@types+react@18.2.78_pg@8.11.3_react@18.2.0/node_modules/drizzle-orm/pg-core/query-builders/query.js:68:60)
    at eval (./node_modules/.pnpm/drizzle-orm@0.29.4_@libsql+client@0.5.6_@types+react@18.2.78_pg@8.11.3_react@18.2.0/node_modules/drizzle-orm/pg-core/query-builders/query.js:114:19)
    at Object.startActiveSpan (./node_modules/.pnpm/drizzle-orm@0.29.4_@libsql+client@0.5.6_@types+react@18.2.78_pg@8.11.3_react@18.2.0/node_modules/drizzle-orm/tracing.js:14:14)
    at QueryPromise.execute (./node_modules/.pnpm/drizzle-orm@0.29.4_@libsql+client@0.5.6_@types+react@18.2.78_pg@8.11.3_react@18.2.0/node_modules/drizzle-orm/pg-core/query-builders/query.js:113:60)
    at QueryPromise.then (./node_modules/.pnpm/drizzle-orm@0.29.4_@libsql+client@0.5.6_@types+react@18.2.78_pg@8.11.3_react@18.2.0/node_modules/drizzle-orm/query-promise.js:26:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
digest: "666803083"
```

**Comment by jmikrut** [comment]
Hey @oladayo21 — here are a few related issues:

#102 
#72 

Take a look at the comments I left on those threads to find the solution. Let me know if you need a hand!
