### ISSUE TITLE
_uuid property is undefined.

### ISSUE THREAD

**Issue by AdvithShetty** [payloadcms/payload-3.0-demo#130]
I created a simple array of media upload in a collection,

```
{
                                    name: 'gallery',
                                    type: 'array',
                                    label: 'Gallery Array',
                                    minRows: 3,
                                    maxRows: 10,
                                    labels: {
                                        singular: 'Item',
                                        plural: 'Items',
                                    },
                                    fields: [
                                        {
                                            name: 'gallery_image',
                                            type: 'upload',
                                            relationTo: 'media',
                                            label: 'Gallery',
                                            filterOptions: {
                                                mimeType: { contains: 'image' },
                                            },
                                        },
                                    ],
                                },
```

After adding above code and uploading these media files and try to save it i am getting an error on terminal shown below:

```
 [15:24:37] ERROR: TypeError: Cannot read properties of undefined (reading '_uuid')
    at transformArray (webpack-internal:///(rsc)/./node_modules/@payloadcms/db-postgres/dist/transform/write/array.js:11:52)
    at eval (webpack-internal:///(rsc)/./node_modules/@payloadcms/db-postgres/dist/transform/write/traverseFields.js:61:90)
    at Array.forEach (<anonymous>)
    at traverseFields (webpack-internal:///(rsc)/./node_modules/@payloadcms/db-postgres/dist/transform/write/traverseFields.js:24:12)
    at eval (webpack-internal:///(rsc)/./node_modules/@payloadcms/db-postgres/dist/transform/write/traverseFields.js:256:13)
    at Array.forEach (<anonymous>)
    at traverseFields (webpack-internal:///(rsc)/./node_modules/@payloadcms/db-postgres/dist/transform/write/traverseFields.js:24:12)
    at eval (webpack-internal:///(rsc)/./node_modules/@payloadcms/db-postgres/dist/transform/write/traverseFields.js:207:29)
    at Array.forEach (<anonymous>)
    at eval (webpack-internal:///(rsc)/./node_modules/@payloadcms/db-postgres/dist/transform/write/traverseFields.js:178:24)
    at Array.forEach (<anonymous>)
    at traverseFields (webpack-internal:///(rsc)/./node_modules/@payloadcms/db-postgres/dist/transform/write/traverseFields.js:24:12)
    at transformForWrite (webpack-internal:///(rsc)/./node_modules/@payloadcms/db-postgres/dist/transform/write/index.js:23:71)
    at upsertRow (webpack-internal:///(rsc)/./node_modules/@payloadcms/db-postgres/dist/upsertRow/index.js:24:101)
    at Object.updateOne (webpack-internal:///(rsc)/./node_modules/@payloadcms/db-postgres/dist/update.js:53:88)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async updateByIDOperation (webpack-internal:///(rsc)/./node_modules/payload/dist/collections/operations/updateByID.js:220:22)
    at async Object.updateByID (webpack-internal:///(rsc)/./node_modules/@payloadcms/next/dist/routes/rest/collections/updateByID.js:23:17)
    at async eval (webpack-internal:///(rsc)/./node_modules/@payloadcms/next/dist/routes/rest/index.js:573:31)
    at async C:\me Projects\me\website\me\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:53238
    at async e_.execute (C:\me Projects\me\website\me\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:44501)
    at async e_.handle (C:\me Projects\me\website\me\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:54492)
    at async doRender (C:\me Projects\me\website\me\node_modules\next\dist\server\base-server.js:1372:42)
    at async cacheEntry.responseCache.get.routeKind (C:\me Projects\me\website\me\node_modules\next\dist\server\base-server.js:1582:40)
    at async DevServer.renderToResponseWithComponentsImpl (C:\me Projects\me\website\me\node_modules\next\dist\server\base-server.js:1502:28)
    at async DevServer.renderPageComponent (C:\me Projects\me\website\me\node_modules\next\dist\server\base-server.js:1919:24)
    at async DevServer.renderToResponseImpl (C:\me Projects\me\website\me\node_modules\next\dist\server\base-server.js:1957:32)
    at async DevServer.pipeImpl (C:\me Projects\me\website\me\node_modules\next\dist\server\base-server.js:915:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\me Projects\me\website\me\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (C:\me Projects\me\website\me\node_modules\next\dist\server\base-server.js:811:17)
    at async C:\me Projects\me\website\me\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\me Projects\me\website\me\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (C:\me Projects\me\website\me\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (C:\me Projects\me\website\me\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (C:\me Projects\me\website\me\node_modules\next\dist\server\lib\router-server.js:353:24)
    at async requestHandlerImpl (C:\me Projects\me\website\me\node_modules\next\dist\server\lib\router-server.js:377:13)
    at async Server.requestListener (C:\me Projects\me\website\me\node_modules\next\dist\server\lib\start-server.js:141:13)
 PATCH /api/institutions/1?depth=0&fallback-locale=null&uploadEdits= 500 in 73ms

```

**Comment by jmikrut** [comment]
Can you provide us with your entire collection? Do you have versions / drafts enabled? Do you have localization enabled? Do you have a custom ID defined?

We will likely need a minimal reproduction for this one but if you can help us with a config, we might not need a full reproduction repo.

**Comment by AdvithShetty** [comment]
Yes i have versions / drafts enabled but i even tried to run this after disabling the feature, gave me the same error. Below is my code for entire collection,

```
import { CollectionConfig } from 'payload/types'
import {lexicalEditor} from '@payloadcms/richtext-lexical'

const Institutions: CollectionConfig = {
    slug: 'institutions',
    admin: {
        useAsTitle: 'institution_name',
    },
    fields: [
        {
            type: 'tabs',
            tabs: [
                {
                    label: 'Main Content',
                    fields: [
                        {
                            type: 'row',
                            fields: [
                                {
                                    name: 'institution_name',
                                    type: 'text',
                                     
                                    admin: {
                                        width: '50%',
                                    },
                                    label: 'Institution Name',
                                },
                                {
                                    name: 'short_description',
                                    type: 'text',
                                     
                                    admin: {
                                        width: '50%',
                                    },
                                    label: 'Short Description',
                                },
                                {
                                    name: 'website',
                                    type: 'text',
                                     
                                    label: 'Website',
                                    admin: {
                                        width: '50%'
                                    }
                                },
                                {
                                    name: 'location',
                                    type: 'text',
                                     
                                    label: 'Location',
                                    admin: {
                                        width: '50%'
                                    }
                                },
                                {
                                    name: 'type',
                                    type: 'radio',
                                     
                                    options: [
                                        {
                                            label: 'Public',
                                            value: 'public'
                                        },
                                        {
                                            label: 'Private',
                                            value: 'private'
                                        }
                                    ],
                                    defaultValue: 'public',
                                    admin: {
                                        layout: 'horizontal',
                                        width: '50%'
                                    }
                                },
                                {
                                    name: 'category',
                                    type: 'select',
                                     
                                    options: [
                                        {
                                            label: 'University',
                                            value: 'university',
                                        },
                                        {
                                            label: 'College',
                                            value: 'college',
                                        },
                                        {
                                            label: 'School',
                                            value: 'school',
                                        },
                                        {
                                            label: 'Both',
                                            value: 'both',
                                        },
                                    ],
                                    admin: {
                                        width: '50%'
                                    }
                                },
                                {
                                    name: 'fee_structure_url',
                                    type: 'text',
                                     
                                    label: 'Fee Structure URL',
                                    admin: {
                                        width: '50%'
                                    }
                                },
                                {
                                    name: 'map_location',
                                    type: 'text',
                                     
                                    label: 'Map Location',
                                    admin: {
                                        width: '50%'
                                    }
                                },
                                {
                                    name: 'facebook_url',
                                    type: 'text',
                                     
                                    label: 'Facebook URL',
                                    admin: {
                                        width: '20%',
                                    }
                                },
                                {
                                    name: 'twitter_url',
                                    type: 'text',
                                     
                                    label: 'Twitter URL',
                                    admin: {
                                        width: '20%',
                                    }
                                },
                                {
                                    name: 'instagram_url',
                                    type: 'text',
                                     
                                    label: 'Instagram URL',
                                    admin: {
                                        width: '20%',
                                    }
                                },
                                {
                                    name: 'linkedin_url',
                                    type: 'text',
                                     
                                    label: 'Linkedin URL',
                                    admin: {
                                        width: '20%',
                                    }
                                },
                                {
                                    name: 'youtube_url',
                                    type: 'text',
                                     
                                    label: 'Youtube URL',
                                    admin: {
                                        width: '20%',
                                    }
                                },

                                {
                                    name: 'keypoints',
                                    type: 'array',
                                    label: 'Keypoints',
                                    minRows: 3,
                                    maxRows: 9,
                                    labels: {
                                        singular: 'keypoint',
                                        plural: 'keypoints',
                                    },
                                    fields: [
                                        {
                                            type: 'row',
                                            fields: [
                                                {
                                                    name: 'keypoint_title',
                                                    type: 'text',
                                                    label: 'Keypoint Title',
                                                    admin: {
                                                        width: '50%'
                                                    },
                                                },
                                                {
                                                    name: 'keypoint_value',
                                                    type: 'text',
                                                    label: 'Keypoint Value',
                                                    admin: {
                                                        width: '50%'
                                                    },
                                                },
                                            ],
                                        },
                                    ],
                                },

                                {
                                    name: 'overview',
                                    type: 'richText',
                                     
                                    label: 'Overview',
                                    admin: {
                                        width: '100%',
                                    },
                                    editor: lexicalEditor({})
                                },


                            ],
                        },
                    ],
                },

                {
                    name: 'media',
                    label: 'Media',
                    fields: [
                        {

                            type: 'row',

                            fields: [
                                {
                                    name: 'logo',
                                    type: 'upload',
                                    relationTo: 'media',
                                     
                                    label: 'Logo',
                                    filterOptions: {
                                        mimeType: { contains: 'image' },
                                    },
                                    admin: {
                                        width: '50%'
                                    }
                                },
                                {
                                    name: 'featured_image',
                                    type: 'upload',
                                    relationTo: 'media',
                                     
                                    label: 'Featured Image',
                                    filterOptions: {
                                        mimeType: { contains: 'image' },
                                    },
                                    admin: {
                                        width: '50%'
                                    }
                                },
                                {
                                    name: 'gallery',
                                    type: 'array',
                                    label: 'Gallery Array',
                                    minRows: 3,
                                    maxRows: 10,
                                    labels: {
                                        singular: 'Item',
                                        plural: 'Items',
                                    },
                                    fields: [
                                        {
                                            name: 'gallery_image',
                                            type: 'upload',
                                            relationTo: 'media',
                                            label: 'Gallery',
                                            filterOptions: {
                                                mimeType: { contains: 'image' },
                                            },
                                        },
                                    ],
                                },
                            ],
                        },
                    ],
                },

                {
                    name: 'ratings',
                    label: 'Rating',
                    fields: [
                        {
                            name: 'overall_rating',
                            type: 'select',
                             
                            label: 'Overall Rating',
                            options: [
                                {
                                    label: 'Platinum',
                                    value: 'platinum',
                                },
                                {
                                    label: 'Diamond',
                                    value: 'diamond',
                                },
                                {
                                    label: 'Gold',
                                    value: 'gold',
                                },
                                {
                                    label: 'Silver',
                                    value: 'silver',
                                },
                                {
                                    label: 'Bronze',
                                    value: 'bronze',
                                },
                            ],

                        },
                        {
                            name: 'subjects',
                            type: 'array',
                            label: 'Subjects',
                            minRows: 3,
                            maxRows: 9,
                            labels: {
                                singular: 'Item',
                                plural: 'Items',
                            },
                            fields: [
                                {
                                    type: 'row',
                                    fields: [
                                        {
                                            name: 'subject_name',
                                            type: 'text',
                                            label: 'Subject Name',

                                            admin: {
                                                width: '50%'
                                            }
                                        },
                                        {
                                            name: 'subject_rating',
                                            type: 'select',

                                            label: 'Subject Rating',
                                            options: [
                                                {
                                                    label: 'Platinum',
                                                    value: 'platinum',
                                                },
                                                {
                                                    label: 'Diamond',
                                                    value: 'diamond',
                                                },
                                                {
                                                    label: 'Gold',
                                                    value: 'gold',
                                                },
                                                {
                                                    label: 'Silver',
                                                    value: 'silver',
                                                },
                                                {
                                                    label: 'Bronze',
                                                    value: 'bronze',
                                                },
                                            ],
                                            admin: {
                                                width: '50%'
                                            }
                                        },
                                    ],
                                },
                            ],
                        },

                        {
                            name: 'video',
                            type: 'text',
                            label: 'Youtube Video URL',
                             
                        }


                    ],

                },

                {
                    name: 'seo',
                    label: 'SEO',
                    fields: [

                    ],
                },
            ],
        },
    ],
    versions: {
        drafts: true,
    },


}

export default Institutions
```

**Comment by HarleySalas** [comment]
I believe this issue is related to the conversation being had here:
[https://discord.com/channels/967097582721572934/1232036122042044446](https://discord.com/channels/967097582721572934/1232036122042044446)

Is this related, or a separate issue?
If you take note of my reproduction steps, I believe a separate issue may still need to be created, as it successfully creates the document, throws the error, then **deletes** the previously created page.

**Comment by jmikrut** [comment]
Hey @HarleySalas — this one is actually fixed in a PR that we are about to merge. Might be related to your issue as well. Checking on that one now!

**Comment by PatrikKozak** [comment]
Hey @AdvithShetty - just merged this [PR](https://github.com/payloadcms/payload/pull/5960) which will fix your issue. Thanks for finding this!

We'll have a release going out in the next couple days!
