### ISSUE TITLE
Can't edit media uploaded to Vercel Blob Storage [Vercel Deployment]

### ISSUE THREAD

**Issue by Augigauki** [payloadcms/payload-3.0-demo#131]
Hi! Got a project on 3.0.0-beta.11 deployed to Vercel using their Postgres and Blob Storage.

I've got a basic Media collection with uploads that have been working fine, but trying to edit a file that's already uploaded (seems to be any field) throws an error and fails to save the changes. 

```
ERROR: FileUploadError: There was a problem while uploading the file.
    at generateFileData (webpack-internal:///(rsc)/./node_modules/.pnpm/payload@3.0.0-beta.11_@swc+core@1.4.13_@swc+helpers@0.5.5__@swc+types@0.1.6/node_modules/payload/dist/uploads/generateFileData.js:62:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async updateByIDOperation (webpack-internal:///(rsc)/./node_modules/.pnpm/payload@3.0.0-beta.11_@swc+core@1.4.13_@swc+helpers@0.5.5__@swc+types@0.1.6/node_modules/payload/dist/collections/operations/updateByID.js:118:61)
    at async Object.updateByID (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+next@3.0.0-beta.11_@types+react@18.2.79_http-status@1.6.2_monaco-editor@0.47.0_ne_q62g7y7l7favhcerv4iaa6qkb4/node_modules/@payloadcms/next/dist/routes/rest/collections/updateByID.js:23:17)
    at async eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+next@3.0.0-beta.11_@types+react@18.2.79_http-status@1.6.2_monaco-editor@0.47.0_ne_q62g7y7l7favhcerv4iaa6qkb4/node_modules/@payloadcms/next/dist/routes/rest/index.js:573:31)      
    at async C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.2.0-canary.33_react-dom@18.2.0_react@18.2.0__react@18.2.0_sass@1.75.0\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:53095
    at async e_.execute (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.2.0-canary.33_react-dom@18.2.0_react@18.2.0__react@18.2.0_sass@1.75.0\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:44464)
    at async e_.handle (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.2.0-canary.33_react-dom@18.2.0_react@18.2.0__react@18.2.0_sass@1.75.0\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:54349)
    at async doRender (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.2.0-canary.33_react-dom@18.2.0_react@18.2.0__react@18.2.0_sass@1.75.0\node_modules\next\dist\server\base-server.js:1365:42)
    at async cacheEntry.responseCache.get.routeKind (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.2.0-canary.33_react-dom@18.2.0_react@18.2.0__react@18.2.0_sass@1.75.0\node_modules\next\dist\server\base-server.js:1575:40)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.2.0-canary.33_react-dom@18.2.0_react@18.2.0__react@18.2.0_sass@1.75.0\node_modules\next\dist\server\base-server.js:1495:28)
    at async DevServer.renderPageComponent (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.2.0-canary.33_react-dom@18.2.0_react@18.2.0__react@18.2.0_sass@1.75.0\node_modules\next\dist\server\base-server.js:1910:24)  
    at async DevServer.renderToResponseImpl (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.2.0-canary.33_react-dom@18.2.0_react@18.2.0__react@18.2.0_sass@1.75.0\node_modules\next\dist\server\base-server.js:1948:32) 
    at async DevServer.pipeImpl (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.2.0-canary.33_react-dom@18.2.0_react@18.2.0__react@18.2.0_sass@1.75.0\node_modules\next\dist\server\base-server.js:911:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.2.0-canary.33_react-dom@18.2.0_react@18.2.0__react@18.2.0_sass@1.75.0\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.2.0-canary.33_react-dom@18.2.0_react@18.2.0__react@18.2.0_sass@1.75.0\node_modules\next\dist\server\base-server.js:807:17)     
    at async C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.2.0-canary.33_react-dom@18.2.0_react@18.2.0__react@18.2.0_sass@1.75.0\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.2.0-canary.33_react-dom@18.2.0_react@18.2.0__react@18.2.0_sass@1.75.0\node_modules\next\dist\trace\trace.js:151:20)
    at async DevServer.handleRequest (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.2.0-canary.33_react-dom@18.2.0_react@18.2.0__react@18.2.0_sass@1.75.0\node_modules\next\dist\server\dev\next-dev-server.js:336:24) 
    at async invokeRender (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.2.0-canary.33_react-dom@18.2.0_react@18.2.0__react@18.2.0_sass@1.75.0\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.2.0-canary.33_react-dom@18.2.0_react@18.2.0__react@18.2.0_sass@1.75.0\node_modules\next\dist\server\lib\router-server.js:353:24)
    at async requestHandlerImpl (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.2.0-canary.33_react-dom@18.2.0_react@18.2.0__react@18.2.0_sass@1.75.0\node_modules\next\dist\server\lib\router-server.js:377:13)        
    at async Server.requestListener (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.2.0-canary.33_react-dom@18.2.0_react@18.2.0__react@18.2.0_sass@1.75.0\node_modules\next\dist\server\lib\start-server.js:142:13)
```

## Steps to reproduce
1. Deploy a Payload 3.0 beta project to Vercel
2. Use Vercel Blob Storage and the vercelBlobAdapter on a collection meant to handle uploads
3. Upload a file to the collection
4. Edit a field on the uploaded item
5. Save the file with the changes made

### Expected result
Item should save to database with new changes

### Actual result
Item fails to save

## Additional info
A workaround is to remove the file and upload it again. This works, but results in the filename getting appended with a number (seems like it creates a new upload altogether).
I have tried creating a new collection with just a basic text field, error still occurs.

**Comment by denolfe** [comment]
Closed by https://github.com/payloadcms/payload/pull/5959
