### ISSUE TITLE
Can't edit media uploaded to Vercel Blob Storage [Vercel Deployment]

### ISSUE THREAD

**Issue by Augigauki** [payloadcms/payload-3.0-demo#158]
Hey again! Still experiencing the issue as described in [this bug report](https://github.com/payloadcms/payload-3.0-demo/issues/131). Error is the same, posting again for clarity:

```
ERROR: FileUploadError: There was a problem while uploading the file.
    at generateFileData (webpack-internal:///(rsc)/./node_modules/.pnpm/payload@3.0.0-beta.18_@swc+core@1.4.13_@swc+helpers@0.5.5__@swc+types@0.1.6_graphql@16.8.1/node_modules/payload/dist/uploads/generateFileData.js:62:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async updateByIDOperation (webpack-internal:///(rsc)/./node_modules/.pnpm/payload@3.0.0-beta.18_@swc+core@1.4.13_@swc+helpers@0.5.5__@swc+types@0.1.6_graphql@16.8.1/node_modules/payload/dist/collections/operations/updateByID.js:118:61)
    at async Object.updateByID (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+next@3.0.0-beta.18_@types+react@18.3.1_file-type@16.5.4_graphql@16.8.1_http-statu_i2uuh553qhyntpjx4w7w7rviuu/node_modules/@payloadcms/next/dist/routes/rest/collections/updateByID.js:25:17)
    at async eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+next@3.0.0-beta.18_@types+react@18.3.1_file-type@16.5.4_graphql@16.8.1_http-statu_i2uuh553qhyntpjx4w7w7rviuu/node_modules/@payloadcms/next/dist/routes/rest/index.js:687:35)
    at async C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.3.0-canary.7_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.75.0\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:53211
    at async e_.execute (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.3.0-canary.7_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.75.0\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:44492)
    at async e_.handle (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.3.0-canary.7_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.75.0\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:54465)
    at async doRender (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.3.0-canary.7_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.75.0\node_modules\next\dist\server\base-server.js:1359:42)     
    at async cacheEntry.responseCache.get.routeKind (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.3.0-canary.7_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.75.0\node_modules\next\dist\server\base-server.js:1573:40)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.3.0-canary.7_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.75.0\node_modules\next\dist\server\base-server.js:1493:28)
    at async DevServer.renderPageComponent (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.3.0-canary.7_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.75.0\node_modules\next\dist\server\base-server.js:1910:24)
    at async DevServer.renderToResponseImpl (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.3.0-canary.7_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.75.0\node_modules\next\dist\server\base-server.js:1948:32)
    at async DevServer.pipeImpl (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.3.0-canary.7_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.75.0\node_modules\next\dist\server\base-server.js:895:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.3.0-canary.7_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.75.0\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.3.0-canary.7_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.75.0\node_modules\next\dist\server\base-server.js:791:17)
    at async C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.3.0-canary.7_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.75.0\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.3.0-canary.7_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.75.0\node_modules\next\dist\trace\trace.js:154:20)    
    at async DevServer.handleRequest (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.3.0-canary.7_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.75.0\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.3.0-canary.7_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.75.0\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.3.0-canary.7_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.75.0\node_modules\next\dist\server\lib\router-server.js:353:24)
    at async requestHandlerImpl (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.3.0-canary.7_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.75.0\node_modules\next\dist\server\lib\router-server.js:377:13)
    at async Server.requestListener (C:\Users\ago03\Documents\Progging\Personal\New-Topographics\node_modules\.pnpm\next@14.3.0-canary.7_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.75.0\node_modules\next\dist\server\lib\start-server.js:141:13)
 PATCH /api/media/117?depth=0&fallback-locale=null 400 in 162ms
```

## Steps to reproduce
1. Deploy a Payload 3.0 beta project to Vercel
2. Use Vercel Blob Storage and the vercelBlobAdapter on a collection meant to handle uploads
3. Upload a file to the collection
4. Edit a field on the uploaded item
5. Save the file with the changes made

### Expected result
Item should save to database with new changes

### Actual result
Item fails to save

## Additional info
A workaround is to remove the file and upload it again. This works, but results in the filename getting appended with a number (seems like it creates a new upload altogether).
I have tried creating a new collection with just a basic text field, error still occurs. I have updated to beta.18, error is still present.

**Comment by denolfe** [comment]
@Augigauki beta.19 is latest. Can you verify if you see it on that version?

**Comment by denolfe** [comment]
I've just tested this with a beta.19 deployment on Vercel, and it appears to be working. Let me know if you see otherwise on that version 👍

**Comment by Augigauki** [comment]
Just updated payload and all dependencies to beta.19 and seems to be working now. Very thankful I don't have to re-upload 119 images in my CMS, thanks a lot!
