### ISSUE TITLE
Code Field Error [Beta 22]

### ISSUE THREAD

**Issue by zelenovsky** [payloadcms/payload-3.0-demo#174]
I use Postgres (beta 22) and have the following Post collection config:
```js
{
     label: 'Dark CSS',
     name: 'theme_dark_css',
     type: 'code',
     admin: {
        language: 'css',
      },
},
```

When I save it in admin pannel I get field data lost and have the following error:

`Cannot read properties of null (reading 'length')
    at CodeCell (index.js:8:33)
    at renderWithHooks (react-dom.development.js:11132:18)
    at mountIndeterminateComponent (react-dom.development.js:16929:13)
    at beginWork (react-dom.development.js:18518:16)
    at performUnitOfWork (react-dom.development.js:25544:12)
    at workLoopSync (react-dom.development.js:25260:5)
    at renderRootSync (react-dom.development.js:25215:7)
    at recoverFromConcurrentError (react-dom.development.js:24393:20)
    at performConcurrentWorkOnRoot (react-dom.development.js:24338:26)
    at workLoop (scheduler.development.js:252:34)
    at flushWork (scheduler.development.js:221:14)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:528:21)`
    
 The same error occurs whenever I try to see Post list, eg `/admin/collections/posts`

**Comment by JessChowdhury** [comment]
[PR #6165](https://github.com/payloadcms/payload/pull/6165) will resolve this issue. [This line](https://github.com/payloadcms/payload/pull/6165/commits/83526da4c68f3682d9cbf9ec411199bbd590c6d2) is causing the problem, we shouldn't render the default components when `cellData` is undefined.

**Comment by JessChowdhury** [comment]
@zelenovsky this fix has been merged and will go out in our next beta release.
