### ISSUE TITLE
Local mode with custom next.js server

### ISSUE THREAD

**Issue by britg** [payloadcms/payload-3.0-demo#185]
I'm trying to use payload as an application framework for a server-only set of script. I'm using the Next.js template for a custom typescript server, here: https://github.com/vercel/next.js/blob/canary/examples/custom-server/README.md

Which extends the default tsconfig with this:

```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "module": "commonjs",
    "outDir": "dist",
    "lib": ["es2019"],
    "target": "es2019",
    "isolatedModules": false,
    "noEmit": false
  },
  "include": ["server.ts"]
}
```

I'm running into this error when trying to import payload into this custom server to use the query engine.

Is it possible to import payload into a custom typescript server at this time?

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/eezo/dungeondaytrader/node_modules/@payloadcms/db-postgres/dist/index.js from /Users/eezo/dungeondaytrader/payload.config.ts not supported.
Instead change the require of index.js in /Users/eezo/dungeondaytrader/payload.config.ts to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (/Users/eezo/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/Users/eezo/dungeondaytrader/payload.config.ts:3:23)
    at m._compile (/Users/eezo/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/Users/eezo/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/Users/eezo/dungeondaytrader/server/src/main.ts:16:42)
    at m._compile (/Users/eezo/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/Users/eezo/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/dist/index.js:859:16)
    at phase4 (/Users/eezo/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/dist/bin.js:466:20)
    at bootstrap (/Users/eezo/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/dist/bin.js:54:12)
    at main (/Users/eezo/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/Users/eezo/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/dist/bin.js:579:5) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by jmikrut** [comment]
Yes, you can use Payload in a custom server, but the problem is that you're setting `module` to `commonjs`. Payload is now fully ESM so you should set your `module` to `esnext`. 

Alternatively, if you want to use CommonJS still, you can, but you'd need to import payload asynchronously like this:

```
const payload = await import('payload') 
```

Does that make sense?

**Comment by britg** [comment]
It does, thank you for the explanation.
