### ISSUE TITLE
Getting error when using locale/language other than english in beta.0

### ISSUE THREAD

**Issue by andershermansen** [payloadcms/payload-3.0-demo#75]
Command:
```
curl -I --header "Accept-Language: en" http://localhost:3001/admin/
```
Gives expected response:
```
HTTP/1.1 307 Temporary Redirect
Vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch, Accept-Encoding
Location: /admin/login?redirect=/admin
Cache-Control: no-store, must-revalidate
X-Powered-By: Next.js
Content-Type: text/html; charset=utf-8
Date: Wed, 10 Apr 2024 06:36:09 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

Command:
```
curl -I --header "Accept-Language: nb" http://localhost:3001/admin/
```
Gives unexpected response:
```
HTTP/1.1 500 Internal Server Error
Vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch, Accept-Encoding
Cache-Control: no-store, must-revalidate
X-Powered-By: Next.js
Content-Type: text/html; charset=utf-8
Date: Wed, 10 Apr 2024 06:36:10 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```
and logs in console:
```
 ⨯ Internal error: TypeError: Cannot read properties of undefined (reading 'translations')
    at getTranslationsByContext (./node_modules/.pnpm/@payloadcms+translations@3.0.0-beta.0/node_modules/@payloadcms/translations/dist/utilities/getTranslationsByContext.js:58:55)
    at eval (./node_modules/.pnpm/@payloadcms+translations@3.0.0-beta.0/node_modules/@payloadcms/translations/dist/utilities/init.js:126:112)
    at memoized (./node_modules/.pnpm/@payloadcms+translations@3.0.0-beta.0/node_modules/@payloadcms/translations/dist/utilities/init.js:118:34)
    at RootLayout (./node_modules/.pnpm/@payloadcms+next@3.0.0-beta.0_@types+react@18.2.74_http-status@1.6.2_monaco-editor@0.47.0_nex_ldpbciivulrrumdli4lejfwyre/node_modules/@payloadcms/next/dist/layouts/Root/index.js:45:90)
```

The error started happening in alpha 61 and is still there in beta 0, alpha 60 was ok.

Probably a regression from https://github.com/payloadcms/payload/pull/5735 @jmikrut

**Comment by andershermansen** [comment]
Understanding the issue from fix and message on discord I fixed it for myself in beta 0 by just installing my wanted translation:
```
import { en } from '@payloadcms/translations/languages/en';
import { nb } from '@payloadcms/translations/languages/nb';
```
```
    i18n: {
        supportedLanguages: { en, nb },
    },
```

**Comment by andershermansen** [comment]
Confirming this is fixed with beta.3 and later.
