### ISSUE TITLE
In `/admin/account` language selector is not working

### ISSUE THREAD

**Issue by galcsikgyozo** [payloadcms/payload-3.0-demo#76]
Trying to select another language instead of **English** produces and error, and the other languages won't load.

<img width="991" alt="Screenshot 2024-04-10 at 16 33 30" src="https://github.com/payloadcms/payload-3.0-demo/assets/60744669/3fbee8c6-2278-4053-9093-904edc005566">

<img width="990" alt="Screenshot 2024-04-10 at 16 33 46" src="https://github.com/payloadcms/payload-3.0-demo/assets/60744669/9ea3b74c-f230-4012-a20e-38a9ad039eb0">

---

Error message in Terminal:
```
 ⨯ TypeError: Response body object should not be disturbed or locked
    at extractBody (node:internal/deps/undici/undici:4507:17)
    at new Request (node:internal/deps/undici/undici:5487:48)
    at new NextRequest (/Users/gyozo/Downloads/payload-3.0-demo-main/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/web/spec-extension/request.js:33:14)
    at NextRequestAdapter.fromNodeNextRequest (/Users/gyozo/Downloads/payload-3.0-demo-main/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/web/spec-extension/adapters/next-request.js:94:16)
    at NextRequestAdapter.fromBaseNextRequest (/Users/gyozo/Downloads/payload-3.0-demo-main/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/web/spec-extension/adapters/next-request.js:70:35)
    at doRender (/Users/gyozo/Downloads/payload-3.0-demo-main/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1363:73)
    at cacheEntry.responseCache.get.routeKind (/Users/gyozo/Downloads/payload-3.0-demo-main/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1574:46)
    at ResponseCache.get (/Users/gyozo/Downloads/payload-3.0-demo-main/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/response-cache/index.js:49:26)
    at DevServer.renderToResponseWithComponentsImpl (/Users/gyozo/Downloads/payload-3.0-demo-main/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1494:53)
```

**Environment details:** Clean install of the packages `3.0.0-beta.0`, and a clean database using the `postgresAdapter`.

**Comment by galcsikgyozo** [comment]
Ah sorry, I've just seen that it was reported by someone else already.

**Comment by jmikrut** [comment]
Hey @galcsikgyozo — this has been fixed, but now, note that you need to install any i18n languages that you want to support into your Payload config.

Check it out here:

https://github.com/payloadcms/payload-3.0-demo/blob/main/payload.config.ts#L88
