### ISSUE TITLE
`/logout` route is returning `Unexpected end of JSON input`

### ISSUE THREAD

**Issue by KeziahMoselle** [payloadcms/payload-3.0-demo#77]
#### Versions

"@payloadcms/db-mongodb": "3.0.0-beta.0",
"@payloadcms/db-postgres": "3.0.0-beta.0",
"@payloadcms/next": "3.0.0-beta.0",
"@payloadcms/richtext-lexical": "3.0.0-beta.0",
"@payloadcms/ui": "3.0.0-beta.0",

I'm calling POST `/logout` route with `payload-token` cookie but no body

<img width="562" alt="image" src="https://github.com/payloadcms/payload-3.0-demo/assets/9168097/6729b2a1-6482-48cd-b45e-657c3901e960">

### Response error

```json
{
  "message": "Unexpected end of JSON input",
  "stack": "SyntaxError: Unexpected end of JSON input\n    at JSON.parse (<anonymous>)\n    at parseJSONFromBytes (node:internal/deps/undici/undici:5329:19)\n    at successSteps (node:internal/deps/undici/undici:5300:27)\n    at fullyReadBody (node:internal/deps/undici/undici:1447:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async specConsumeBody (node:internal/deps/undici/undici:5309:7)\n    at async getDataAndFile (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+next@3.0.0-beta.0_@types+react@18.2.75_http-status@1.6.2_monaco-editor@0.47.0_nex_6vm2hw4ero6olxzv5pgmgzfg6q/node_modules/@payloadcms/next/dist/utilities/getDataAndFile.js:17:20)\n    at async createPayloadRequest (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+next@3.0.0-beta.0_@types+react@18.2.75_http-status@1.6.2_monaco-editor@0.47.0_nex_6vm2hw4ero6olxzv5pgmgzfg6q/node_modules/@payloadcms/next/dist/utilities/createPayloadRequest.js:38:28)\n    at async eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+next@3.0.0-beta.0_@types+react@18.2.75_http-status@1.6.2_monaco-editor@0.47.0_nex_6vm2hw4ero6olxzv5pgmgzfg6q/node_modules/@payloadcms/next/dist/routes/rest/index.js:332:19)\n    at async /Users/keziah/Sites/Personnel/soulsborne.build/backend/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:52954\n    at async e_.execute (/Users/keziah/Sites/Personnel/soulsborne.build/backend/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:44464)\n    at async e_.handle (/Users/keziah/Sites/Personnel/soulsborne.build/backend/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:54208)\n    at async doRender (/Users/keziah/Sites/Personnel/soulsborne.build/backend/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1364:42)\n    at async cacheEntry.responseCache.get.routeKind (/Users/keziah/Sites/Personnel/soulsborne.build/backend/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1574:40)\n    at async DevServer.renderToResponseWithComponentsImpl (/Users/keziah/Sites/Personnel/soulsborne.build/backend/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1494:28)\n    at async DevServer.renderPageComponent (/Users/keziah/Sites/Personnel/soulsborne.build/backend/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1909:24)\n    at async DevServer.renderToResponseImpl (/Users/keziah/Sites/Personnel/soulsborne.build/backend/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1947:32)\n    at async DevServer.pipeImpl (/Users/keziah/Sites/Personnel/soulsborne.build/backend/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:910:25)\n    at async NextNodeServer.handleCatchallRenderRequest (/Users/keziah/Sites/Personnel/soulsborne.build/backend/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:272:17)\n    at async DevServer.handleRequestImpl (/Users/keziah/Sites/Personnel/soulsborne.build/backend/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:806:17)\n    at async /Users/keziah/Sites/Personnel/soulsborne.build/backend/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:339:20\n    at async Span.traceAsyncFn (/Users/keziah/Sites/Personnel/soulsborne.build/backend/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/trace/trace.js:151:20)\n    at async DevServer.handleRequest (/Users/keziah/Sites/Personnel/soulsborne.build/backend/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:336:24)\n    at async invokeRender (/Users/keziah/Sites/Personnel/soulsborne.build/backend/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:174:21)\n    at async handleRequest (/Users/keziah/Sites/Personnel/soulsborne.build/backend/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:353:24)\n    at async requestHandlerImpl (/Users/keziah/Sites/Personnel/soulsborne.build/backend/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:377:13)\n    at async Server.requestListener (/Users/keziah/Sites/Personnel/soulsborne.build/backend/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/start-server.js:142:13)"
}
```

**Comment by jacobsfletch** [comment]
@KeziahMoselle just to clarify, you're posting to `/api/users/logout` right? There is to `/logout` API route at the root.

**Comment by KeziahMoselle** [comment]
Oh yes sorry I'm proxying my request `/api/users/logout` to Payload and i'm getting this error (login is fine!)

**Comment by jacobsfletch** [comment]
@KeziahMoselle thank you for reporting this 👍 I've got a fix queued up in https://github.com/payloadcms/payload/pull/5797 which should go out in the next beta release

**Comment by KeziahMoselle** [comment]
Awesome! Thank you ❤️
