### ISSUE TITLE
ERROR: APIError: This collection has local storage disabled

### ISSUE THREAD

**Issue by j-palindrome** [payloadcms/payload-3.0-demo#92]
I have an uploads collection using `disableLocalStorage` which is throwing an error on every upload (it still functions I think, but the error flashes in the console). I'm using a hook to convert video/images to webm/webp and limit the dimensions, so I write the files myself.

In particular, the error happens when uploading from a separate collection:

```
{
  ...
  fields: [
    ...
    {
      name: 'banner',
      type: 'upload',
      relationTo: 'banners',
      required: true
    },
  ]
}
```

```
import { CollectionConfig } from 'payload/types'
import hooks from '../hooks/resize'

const Banners: CollectionConfig = {
  slug: 'banners',
  fields: [
    ...
  ],
  upload: {
    mimeTypes: ['video/*', 'image/*'],
    staticDir: 'media',
    disableLocalStorage: true,
  },
  hooks: {
    beforeChange: [hooks.acceptBanner],
  },
}

export default Banners
```

```
ERROR: APIError: This collection has local storage disabled: banners
    at Object.getFile (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+next@3.0.0-beta.3_@types+react@18.2.75_http-status@1.6.2_monaco-editor@0.47.0_nex_zdvjqc2qdf3g5bs6ut4y2egaxy/node_modules/@payloadcms/next/dist/routes/rest/files/getFile.js:25:19)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+next@3.0.0-beta.3_@types+react@18.2.75_http-status@1.6.2_monaco-editor@0.47.0_nex_zdvjqc2qdf3g5bs6ut4y2egaxy/node_modules/@payloadcms/next/dist/routes/rest/index.js:233:66)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/jreinier/Documents/1_now/web-design/4-10/jpalindrome/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:52954
    at async e_.execute (/Users/jreinier/Documents/1_now/web-design/4-10/jpalindrome/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:44464)
    at async e_.handle (/Users/jreinier/Documents/1_now/web-design/4-10/jpalindrome/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:54208)
    at async doRender (/Users/jreinier/Documents/1_now/web-design/4-10/jpalindrome/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1364:42)
    at async cacheEntry.responseCache.get.routeKind (/Users/jreinier/Documents/1_now/web-design/4-10/jpalindrome/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1574:40)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/jreinier/Documents/1_now/web-design/4-10/jpalindrome/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1494:28)
    at async DevServer.renderPageComponent (/Users/jreinier/Documents/1_now/web-design/4-10/jpalindrome/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1909:24)
    at async DevServer.renderToResponseImpl (/Users/jreinier/Documents/1_now/web-design/4-10/jpalindrome/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1947:32)
    at async DevServer.pipeImpl (/Users/jreinier/Documents/1_now/web-design/4-10/jpalindrome/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:910:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/jreinier/Documents/1_now/web-design/4-10/jpalindrome/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/Users/jreinier/Documents/1_now/web-design/4-10/jpalindrome/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:806:17)
    at async /Users/jreinier/Documents/1_now/web-design/4-10/jpalindrome/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/jreinier/Documents/1_now/web-design/4-10/jpalindrome/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/trace/trace.js:151:20)
    at async DevServer.handleRequest (/Users/jreinier/Documents/1_now/web-design/4-10/jpalindrome/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/jreinier/Documents/1_now/web-design/4-10/jpalindrome/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/Users/jreinier/Documents/1_now/web-design/4-10/jpalindrome/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/Users/jreinier/Documents/1_now/web-design/4-10/jpalindrome/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/Users/jreinier/Documents/1_now/web-design/4-10/jpalindrome/node_modules/.pnpm/next@14.2.0-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/start-server.js:142:13)
```

**Comment by JarrodMFlesch** [comment]
The issue has been addressed in [this PR](https://github.com/payloadcms/payload/pull/5896)!

Thanks for reporting 👍
